events {}

http {
    server {
        listen 80;

        location /laravel/ {
            proxy_pass http://laravel:8000/;
        }

        location /node/ {
            proxy_pass http://node:3000/;
        }

        location /python/ {
            proxy_pass http://python:8000/;
        }

        location /csharp/ {
            proxy_pass http://dotnet_csharp:8080/;
        }

        location /vb/ {
            proxy_pass http://dotnet_vb:8080/;
        }

        location /java/ {
            proxy_pass http://java:8080/;
        }

        location /wordpress/ {
            proxy_pass http://wordpress:80/;
        }

        location /codeignite/ {
            proxy_pass http://codeigniter:80/;
        }
    }
}